                                                                                                                                          
                                                    ':ccccc:'                                            
                                                 ,oKd:,'.',:loo,                                            
                                              ,do'oNl........,od,                                           
                                              :k,...cNx.........,k:                                         
                                             ,O'''''',00,'''''''''O,                                        
                                             ol       'xX:'       oo                                      
                                             dl:dolod':lN'ooooooxOKd                                    
                                             ;O''0'''',X'X,'''''klO;                       
                                              ox,kl,''lXodxc,,;okko,                                     
                                              ,dO,loooOx;kolooo:0o,                                      
                                              :K;,,,,,koook,,,,,:K:                                        
                                               odoo;,lo:,:ol,;oodo                                          
                                                  Olok:K;K:Oolk                                           
                                                  :oo; ldl :dd:                                        
                                                                                                                        
                                                                                                                 
                                                                                                                 
                                                                                                                 
                                                                        
                                                                                                                      
                                                                                                              
                                              ...............                                                 
                                             ........,:;,.........                                            
                                      ..........';lxk000Okdc;........                                        
                                    ........,:dkO00KK0000O000Okoc,........                                    
                                .  .....':ok0K00000KKKK0K00K000O00ko:'......                                  
                                  ..,cdkkO00K00OK0K0KXKKKKKKKKO00KK00OOdc,...                                 
                                  .c000Olo0xdxxc00KKK00K0KKKKKlkkkk0ooOO0Kl...                                
                                 ..oOOOO0l'...,xK000KKKKK0K0KKx;'..,lOOOOOo....                               
                                ...o0OO0:......,xK00KKKK0KKKKd'......l0Okko....                               
                                ...o0olk........ckd0KK0K0K0oOc'......'OooOo...                                
                               ....l0OxO.......'oOkKKKKKKKKx0o''.....'OkOOo... .                              
                             ......oKKKKo....''lKXXXKXXXXXXKXKl'''..'dKKKOd....                               
                              .....dNNNN0koccdOKNNNNNNNNNNNNNN0OoccokKNNNXx......                             
                              ....'lXWWWOkNWWWKkNWWWWNKKNWWWWNkKWWWNk0WWNXl'.....                             
                                 ....;okKNO0XNNNNNNNXddddXNNNNNNNX00NXOd:'....                                
                                   ......,''kXXNKXNNNNNNNNNNXXNNXx',;......                                   
                                     .......dXXXo0XX0KXXKKXX0oXXXd'.......                                    
                                       ......,lx:OXXxkXXkkXNOcxl;'......                                      
                                          .......,cdcxXXdcdc,..........                                       
                                              ........;;............                                          
                                                ..   ..........                                               
                                                      ...                                                     
                                                                                                              
                                                                                             .                            .                                        
                                       .                              .                                       
                                      .                                .                                      
                                       .                              .                                       
                                         .                          .                                         
                                          .                        .                                          
                                           ..                    ..                                           
                                             .                  .                                             
                .                             ..................                             .                
                 .                          .....:olllccllll:.....                          .                 
                  .                        ....looNo.......'col'...                        .                  
                   ..                     ...;k;..,Kk'........:k;...                     ..                   
                    ..                   ...,k'...''kK;'''''''''O,''.                   ..                    
                      .                 .'''k:'''''''lNc''''''''cx'''.                 .                      
                       .               .''''0,'':olloccNxlllloodx0'''''               .                       
                        ..............''''''dl':O,'''dcdo''''':0ko''''''..............                        
                       .              .''''',k::O,'',xxlkc,',:kdk,,,,,'.             ..                       
                      .                 ''''',Oc;ooodKlokloooloO,,,,,'                 .                      
                     .                   ',,,lk;,,,,ckooOc,,,,;Ol,,,'                   ..                    
                   ..                     ',,;ddoc,;lc;;ll;,codx;,,'                     ..                   
                  ..                       .,,,,;0:0cklokcO:0:,,,,.                       ..                  
                 ..                         .,,,,:oc,;oo;,co:;;;,.                         ..                 
                .                            .;,,,,,;;;;;;;;;;;;.                           ..                
                                             ..                ..                                             
                                            ..                  ..                                            
                                           .                      '                        
                                                                                                              
                                                                                                                                 
